Repository kodos-prj/kodos, pull requests merged in 2024-11, with the labels that each got.

#2 Cleanup code
  example/config.lua
  kod/commands.py
  notes.md
Labels: code cleanup

#4 Adding aur support
  example/config.lua
  kod/commands.py
Labels: enhancement, code cleanup

#5 Added disk definition as lua function
  example/config.lua
  example/disk.lua
  example/utils.lua
Labels: enhancement

#6 Add support for hardware and service sections
  example/config.lua
  kod/commands.py
Labels: enhancement
