Repository kodos-prj/kodos, pull requests merged in 2025-01, with the labels that each got.

#20 Support for read only /usr (inmutability)
  example/simple.lua
  kod/commands.py
Labels: enhancement, code cleanup

#23 Fix locale generation and dconf configuration
  hosts/eszkoz/eszkoz.lua
  hosts/eszkoz/gnome.lua
  hosts/testvm/gnome.lua
  hosts/testvm/testvm.lua
  kod/commands.py
  kod/lib/configs.lua
Labels: bug

#24 New fs hierarchy using bind
  hosts/testvm/cli-testvm.lua
  kod/commands.py
Labels: enhancement

#25 Add user groups
  hosts/testvm/cli-testvm.lua
  hosts/testvm/testvm.lua
  kod/commands.py
Labels: enhancement

#26 New cli framework
  flake.nix
  hosts/eszkoz/eszkoz.lua
  hosts/testvm/gnome.lua
  kod/common.py
  kod/filesytem.py
  kod/kod.py
  kod/main.py
  pyproject.toml
Labels: enhancement, code cleanup
